--创建一个数据库
CREATE DATABASE music_ DEFAULT CHARACTER SET UTF8;

--切换数据库
USE music_

--创建测试数据库表
CREATE TABLE demo(
  `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  `name` VARCHAR(20) NOT NULL UNIQUE COMMENT '名字'
)ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET UTF8 COMMENT="测试表";
